networks:
  ai_tutorials-network:
    name: ${COMPOSE_PROJECT_NAME:-default}-ai_tutorials-network
secrets:
  package:
    file: secrets/package.txt
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME:-default}_ai_tutorials_nginx
    env_file: .env
    environment:
      PORT_NGINX: ${PORT_NGINX}
    image: nginx:alpine
    networks:
    - ai_tutorials-network
    ports:
    - ${PORT_NGINX}:80
    restart: always
    volumes:
    - ../docs/_build/html:/usr/share/nginx/html:ro
  python:
    build:
      context: ..
      dockerfile: docker/pytorch.Dockerfile
      shm_size: 1g
    cap_add:
    - SYS_PTRACE
    container_name: ${COMPOSE_PROJECT_NAME:-default}_ai_tutorials_python
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
    env_file: .env
    environment:
    - ENVIRONMENT=${ENVIRONMENT}
    - PORT_DASH=${PORT_DASH}
    - PORT_GOOGLE=${PORT_GOOGLE}
    - PORT_JUPYTER=${PORT_JUPYTER}
    - PORT_MLFLOW=${PORT_MLFLOW}
    - PORT_PROFILE=${PORT_PROFILE}
    - PORT_RAY_DASHBOARD=${PORT_RAY_DASHBOARD}
    - PORT_RAY_SERVER=${PORT_RAY_SERVER}
    image: ai_tutorials_python
    ipc: host
    networks:
    - ai_tutorials-network
    ports:
    - ${PORT_DASH}:${PORT_DASH}
    - ${PORT_GOOGLE}:${PORT_GOOGLE}
    - ${PORT_JUPYTER}:${PORT_JUPYTER}
    - ${PORT_MLFLOW}:5000
    - ${PORT_PROFILE}:${PORT_PROFILE}
    - ${PORT_RAY_DASHBOARD}:${PORT_RAY_DASHBOARD}
    - ${PORT_RAY_SERVER}:${PORT_RAY_SERVER}
    restart: always
    secrets:
    - package
    shm_size: 24g
    tty: true
    ulimits:
      memlock: -1
    volumes:
    - ..:/usr/src/ai_tutorials
    - ${DATA_DIR}:/usr/src/ai_tutorials/data
    - ai_tutorials-secret:/usr/src/ai_tutorials/docker/secrets
  streamlit:
    build:
      context: ..
      dockerfile: docker/streamlit.Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-default}_ai_tutorials_streamlit
    env_file: .env
    environment:
      PORT_STREAMLIT: ${PORT_STREAMLIT}
    image: ai_tutorials_streamlit
    networks:
    - ai_tutorials-network
    ports:
    - $PORT_STREAMLIT:8501
    restart: always
    volumes:
    - ../applications/streamlit:/usr/src/ai_tutorials/applications/streamlit
volumes:
  ai_tutorials-secret: null
